version: '3'

services:
  app1:
    build:
      context: .
      dockerfile: pyapp/Dockerfile
    ports:
      - "5001:5001"
    command: [ "python", "/usr/src/app/app.py", "5001", "1" ]

  app2:
    build:
      context: .
      dockerfile: pyapp/Dockerfile
    ports:
      - "5002:5002"
    command: [ "python", "/usr/src/app/app.py", "5002", "2" ]
